# Nome do Workflow
name: Spotmusic Front Pipeline
# Evento que irá acionar a pipeline
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev/
      - name: Build Image & Push
        env:
          ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/spotfront:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/spotfront:latest
  DeployProd:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Auth GCP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Deploy to Cloud run
        id: cloudrun
        env:
          ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
      - name: Deploy Frontend no  Cloud Run
        id: deploy
        run: |-
          gcloud run deploy frontend \
            --quiet \
            --region us-central1 \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/spotfront:latest \
            --platform managed \
            --allow-unauthenticated \
            --project hackathon-7aso-grupo-01\
            --format json


      - name: Prod Test
        run: 'curl "${{ steps.appengine.outputs.url }}"'